name: Build

on:
  push:
    branches: [ native-cli ]
  pull_request:
    branches: [ native-cli ]
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    
    strategy:
      matrix:
        include:
          - os: windows
            arch: x86_64
            runner: windows-latest
            rid: win-x64
          - os: windows
            arch: aarch64
            runner: windows-latest
            rid: win-arm64
          - os: macos
            arch: x86_64
            runner: macos-15
            rid: osx-x64
          - os: macos
            arch: aarch64
            runner: macos-15
            rid: osx-arm64
          - os: linux
            arch: x86_64
            runner: ubuntu-latest
            rid: linux-x64
          - os: linux
            arch: aarch64
            runner: ubuntu-24.04-arm
            rid: linux-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore Il2CppInspectorRedux.CLI/Il2CppInspectorRedux.CLI.csproj

      - name: Build
        run: dotnet build Il2CppInspectorRedux.CLI/Il2CppInspectorRedux.CLI.csproj --configuration Debug --no-restore

      - name: Publish
        run: dotnet publish Il2CppInspectorRedux.CLI/Il2CppInspectorRedux.CLI.csproj --configuration Debug --runtime ${{ matrix.rid }} --output ./publish/${{ matrix.rid }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.rid }}
          path: publish/${{ matrix.rid }}